[package]
name = "arp-spoof"
version = "0.3.0"
authors = ["gcarq <egger.m@protonmail.com>"]
edition = "2021"

[dependencies]
pcap = "^1.0.0"
argparse = "^0.2"
nix = "^0.26.2"
clap = { version = "4.4.2", features = ["derive"] }
